### ISSUE TITLE
Cannot read properties of undefined (reading 'version')

### ISSUE THREAD

**Issue by KIMKYEONGYONG** [jquery/jquery-ui#2216] opened 2024-03-12 10:24 UTC
npm jquery 1.13.2

my source 

import jQueryUi  from "jquery-ui"

 jQueryUi(".lbox ul").draggable({
            containment: "parent"
        });
        jQueryUi(".lbox ul").resizable();
        
error!! 
message : 
Uncaught TypeError: Cannot read properties of undefined (reading 'version')
    at $.widget (widget.js:93:1)
    at HTMLDivElement.<anonymous> (material_banner.js:56:17)
    at HTMLDocument.dispatch (jquery.js:5145:1)
    at elemData.handle (jquery.js:4949:1)

**Comment by mgol** [comment] 2024-03-12 23:25
Thanks for the report. Can you provide a test case on [JS Bin](https://jsbin.com/qawicop/edit?html,css,js,output) or a similar site?

Also, does the problem exist just in jQuery UI 1.13 or also in 1.12 or older?

**Comment by KIMKYEONGYONG** [comment] 2024-03-13 00:33
umm. 1.13.1 and 1.13.0 is error!  
ver < 1.13 no test

**Comment by mgol** [comment] 2024-03-13 07:23
Thanks for the report. Since the issue is already in 1.12, given limited team resources it's not likely to be fixed by the UI team; see the project status at https://blog.jqueryui.com/2021/10/jquery-maintainers-update-and-transition-jquery-ui-as-part-of-overall-modernization-efforts/. PRs are welcome if they're not too complex.

**Comment by mgol** [comment] 2024-03-13 07:29
I am leaving the "Needs info" label as we still don't have enough information, in addition to all I wrote above.

**Closed** 2024-03-27 06:12 UTC
Labels: Behavior shared with 1.12, Needs info
