### ISSUE TITLE
Uncaught TypeError: this.dragDirection is undefined

### ISSUE THREAD

**Issue by gtbu** [jquery/jquery-ui#2151] opened 2023-01-23 19:22 UTC
I changed in Typesetter CMS from UI 11.4 to 13.2 and suddenly get in the pagemanager the error in sortable.js :  Uncaught TypeError:[ this.dragDirection is ](https://github.com/gtbu/Typesetter-5.3-p8/blob/main/include/thirdparty/jquery_ui/sortable.js#L437)undefined . 
 The string ' dragDirection' exists only in sortable.js 13.2 (with sortable.js  v11.4 and ui 13.2 everything functions - and in sortable v11.4 exists no 'this.dragDirection' - so it must be the debugger : this.dragDirection exists 4 times in sortable.js 13.2)
Is it really undefined , and if - how can i define the Type  ?  ---  var  dragDirection ="";  in  line 410 has no effect ?
P.S. This error is not under Xampp but only in Web-installations.

**Comment by mgol** [comment] 2023-01-24 01:41
Are you using the nestedSortable jQuery plugin? If so, it’s a duplicate of #1997.

**Comment by gtbu** [comment] 2023-01-24 10:40
Yes - replacement of nested sortable 1.34 with version 2.1a solves the problem.

**Closed** 2023-01-24 10:40 UTC
Labels: Needs info
