### ISSUE TITLE
jQuery UI Dialog content shrinks when continuously resizing

### ISSUE THREAD

**Issue by Josh-Reichman** [jquery/jquery-ui#2083] opened 2022-06-03 20:29 UTC
When reducing the size of a dialog when the content has a scroll bar, it continuously shrinks each time you click (as in click down, move, click up, repeat). I've tested this on Chrome (102.0.5005.63), Edge (102.0.1245.33), and Firefox (101.0). Firefox works fine while Chrome and Edge do not. 

I've attached a video with the bug
https://user-images.githubusercontent.com/9708451/171943601-c9fc6e38-cb7a-47fa-881a-1999e4b08748.mp4

I can try to give more info if needed. I'm unsure if this is related to https://github.com/jquery/jquery-ui/issues/1979 but it appears that issue hasn't been updated since last year

**Comment by Josh-Reichman** [comment] 2022-06-03 20:35
I'm not sure what jQuery and jQuery ui versions are being used on the jQuery ui site but I can confirm this is an issue when using jquery ui 1.13.1 and jquery core 3.6.0 for my application I am working on.

**Comment by mgol** [comment] 2022-06-22 10:52
Thanks for the report. This looks like a 1.13 regression as I can't reproduce the behavior on an older version of the website that used 1.12.1:
https://web.archive.org/web/20190308021648/https://jqueryui.com/dialog/
It's not just a Web Archive thing as the archived latest version of the site using 1.13.1 has the issue:
https://web.archive.org/web/20220622032021/https://jqueryui.com/dialog/

**Comment by Josh-Reichman** [comment] 2022-10-27 20:04
@mgol I saw #1979 was updated with a commit earlier this month. Do you know if it fixed this issue? If it did, this issue can be closed.

**Comment by mgol** [comment] 2022-11-18 12:52
@Josh-Reichman Yes, it looks like it was fixed by #1979, see: https://jsfiddle.net/m_gol/Lgnfyuk4/3/

Thanks for the note! The fix will be included in jQuery UI 1.13.3.

**Closed by mgol** 2022-11-18 12:52 UTC
Labels: Bug, Comp: Dialog, Behavior different from 1.12

**Comment by Josh-Reichman** [comment] 2022-11-18 14:43
Fantastic! My team will be glad this will be fixed for our application. Thanks @mgol!

**Comment by mgol** [comment] 2023-12-14 16:41
@slominskir jQuery UI is in maintenance mode (see the project status at https://blog.jqueryui.com/2021/10/jquery-maintainers-update-and-transition-jquery-ui-as-part-of-overall-modernization-efforts/) so the activity is limited. You can help getting the release out the door quicker by submitting PRs for [open `1.13.3` issues](https://github.com/jquery/jquery-ui/milestone/6) and by submitting fixes for current test failures - see the red entries at https://swarm.jquery.org/project/jqueryui and the Next page; everything run last Sunday / Monday.

Otherwise, you need to wait until I have time to address those issues. Considering my main focus right now is the jQuery 4.0.0 release, it may take a while.

**Comment by slominskir** [comment] 2023-12-14 17:23
@mgol I appreciate your efforts. 

![dependency](https://imgs.xkcd.com/comics/dependency.png)
https://xkcd.com/2347/

A shame [a single IE issue](https://github.com/jquery/jquery-ui/issues/2190) is holding up the release (should IE be dropped in newer releases?).   Also, the release process must be very onerous to sit on a fix for a regression that has been already solved ([release more often?](http://www.catb.org/~esr/writings/cathedral-bazaar/cathedral-bazaar/ar01s04.html)).  Looks like the fiddle above uses a pre-release that might resolve this though:  https://releases.jquery.com/git/ui/jquery-ui-git.js

**Comment by mgol** [comment] 2023-12-14 18:15
It's not just a single IE issue; there are some test failures with some browser/jQuery combinations that you can see at https://swarm.jquery.org/job/14283; this is the bigger issue that I think absolutely need solving before a release.

**Comment by slominskir** [comment] 2023-12-18 15:37
Presumably a pull request is not merged unless it passes the tests so I'm assuming the test failures are created each time a new version of a browser is released things break?  Seems like incrementally adding value to the project (with a release containing a subset of all possible fixes) would be a reasonable approach (especially considering the latest stable version has at least the regression mention in this ticket and bug free releases are impractical).

**Comment by mgol** [comment] 2023-12-18 17:18
> Presumably a pull request is not merged unless it passes the tests

We are not running all tests with all supported jQuery versions against all supported browsers in the PR builder; that's a complicated task and we're not going to achieve it here anymore.

Basic testing is done but that's mostly basic Chromium tests against a fixed jQuery version.
