### ISSUE TITLE
SelectMenu Demo Error

### ISSUE THREAD

**Issue by KnowHowIs** [jquery/jquery-ui#2241] opened 2024-04-22 02:33 UTC
I'm getting an error with the latest version of Chrome.

If you click on the select box from the sample code
"status-stack-overflow" chrome error.

sample code url : https://jqueryui.com/selectmenu/
chrome version : 124.0.~~~

**Comment by mgol** [comment] 2024-04-22 16:59
For the record, this is the page I'm seeing:
<img width="689" alt="Screenshot 2024-04-22 at 18 58 36" src="https://github.com/jquery/jquery-ui/assets/1758366/89836084-b93b-4557-abff-fc3412e07c4f">

**Comment by mgol** [comment] 2024-04-22 21:16
Yeah, I think we'll need to wait for a Chrome patch. The issue affects multiple large frameworks so they should treat it with high priority.

I'll leave this open for now until the fix lands for easier searching but I don't expect us to do anything here.

**Comment by mgol** [comment] 2024-04-25 23:09
The issue is fixed in versions >=124.0.6367.91. I verified it works fine now on 124.0.6367.93 on macOS. Closing the issue.

**Closed by mgol** 2024-04-25 23:09 UTC
