### ISSUE TITLE
1.13.0 bug in sortable, draggable: freezes page, "this.dragDirection" is undefined

### ISSUE THREAD

**Issue by danbernier** [jquery/jquery-ui#1997] opened 2021-10-19 18:05 UTC
Upgrading jquery-ui from 1.12.1 to 1.13.0 seems to have introduced an exception coming from sortable.

jQuery: 3.6.0
jquery-ui: 1.13.0 (not present in 1.12.1)

When you first drag a sortable component, the page freezes, and this error appears in the console:

```
Uncaught TypeError: Cannot read properties of undefined (reading 'vertical')
    at $.<computed>.<computed>._intersectsWithPointer (sortable.js:595)
    at $.<computed>.<computed>.<anonymous> (widget.js:123)
    at $.<computed>.<computed>._intersectsWithPointer (widget.js:123)
    at $.<computed>.<computed>._mouseDrag (jquery.mjs.nestedSortable.js:203)
    at $.<computed>.<computed>._mouseDrag (widget.js:123)
    at $.<computed>.<computed>._mouseStart (sortable.js:316)
    at $.<computed>.<computed>.<anonymous> (widget.js:123)
    at $.<computed>.<computed>._mouseStart (widget.js:123)
    at $.<computed>.<computed>._mouseMove (mouse.js:150)
    at $.<computed>.<computed>.<anonymous> (widget.js:123)
```

It looks to come from [this line in sortable.js](https://github.com/jquery/jquery-ui/blob/1f0851b5381143e78d4ded1877b2a0e4d2aec5ca/ui/widgets/sortable.js#L699), while evaluating `this.dragDirection.vertical`.

The only recent commit to sortable.js is 70dae67b73dfea9126f126f516fe8286f1e73417, but [the file history](https://github.com/jquery/jquery-ui/commits/main/ui/widgets/sortable.js) shows a few other commits that I think were added after 1.12.1, so that may be misleading.

This seems to have a lot in common with issue #1991, though I suspect they're distinct.

**Comment by mgol** [comment] 2021-11-07 10:57
@danbernier A gentle reminder about a test case. :)

**Comment by mgol** [comment] 2021-11-15 17:38
@danbernier Another friendly ping. :)

**Comment by jwcooper** [comment] 2021-11-15 17:56
Here is a demo showing the issue using nestedSortable and their default example:
https://jsbin.com/mizadimobu/2/edit?html,css,js,output

With jquery ui 1.12.1 it works fine, on 1.13.0 it throws the error. Sorry I don't have a simpler example for you, this is just one that we ran into, forcing us to rollback to 1.12.1 for now.

**Comment by danbernier** [comment] 2021-11-16 17:11
Thanks @jwcooper! Sorry this got away from me @mgol. @jwcooper's looks about like what mine would've been.

**Comment by mgol** [comment] 2021-11-18 22:12
@jwcooper From what I see, the jQuery UI Nested Sortable library overwrites some methods in `$.ui.sortable.prototype`, in particular the private `_mouseDrag` method. When you do that, all bets are off. And, indeed, their version of `_mouseDrag` doesn't set the `dragDirection` property which is then used in other methods. That needs to be fixed in jQuery UI Nested Sortable.

@jwcooper are you by any chance using the same jQuery UI Nested Sortable library?

**Comment by mgol** [comment] 2021-11-18 22:17
I don't think there's anything to be done on the jQuery UI side here. The bug is in the jQuery UI Nested Sortable library, the way it overwrote private parts of the Sortable widget has always been risky. The library doesn't look maintained, with the last commit being done 4 years ago. Your best bet may be forking the library and backporting jQuery UI 1.13.0 changes to it. For this specific issue, the most important is this bit of `_mouseDrag`: https://github.com/jquery/jquery-ui/blob/1.13.0/ui/widgets/sortable.js#L442-L445. I can't guarantee there won't be more changes to backport until it stops being broken, though.

I'm going to close this since the issue is not in UI but feel free to continue discussing the issue here.

**Closed by mgol** 2021-11-18 22:17 UTC
Labels: Bug, Comp: Draggable, Comp: Sortable, Behavior different from 1.12, Needs info

**Comment by jwcooper** [comment] 2021-12-06 19:11
@mgol Thanks for the tip on issue and the fix, really appreciate it. It was indeed nested sortable that broke, and adding the dragDirection (and a few more things) worked with 1.13.
