### ISSUE TITLE
Please update NPM jquery-ui-dist to 1.13.1

### ISSUE THREAD

**Issue by Andrewiski** [jquery/jquery-ui#2047] opened 2022-02-05 16:10 UTC
A lot of node developers use the jquery-ui-dist package to get the min versions of jquery-ui into there projects.  Can someone update that package so it also uses 1.13.1?

https://www.npmjs.com/package/jquery-ui-dist/v/1.13.0

**Comment by mgol** [comment] 2022-02-08 01:04
Please search for existing issues before submitting new ones. A dupe of #2044.

**Closed by mgol** 2022-02-08 01:04 UTC
