### ISSUE TITLE
Wrong outline in dialog close button on Firefox

### ISSUE THREAD

**Issue by flack** [jquery/jquery-ui#2003] opened 2021-11-01 08:24 UTC
The basic demo (https://jqueryui.com/dialog/) shows a focus outline like this on Firefox: 

<img width="631" alt="Bildschirmfoto 2021-11-01 um 09 19 36" src="https://user-images.githubusercontent.com/425166/139642747-9ce63b03-40c0-4ab5-980a-442f25ad79b9.png">

It seems to work fine in Chrome, haven't checked other browsers

**Comment by mgol** [comment] 2021-11-07 10:55
Thanks for the report. Since the issue is already in 1.12, it's not likely to be fixed by the UI team; see the project status at https://blog.jqueryui.com/2021/10/jquery-maintainers-update-and-transition-jquery-ui-as-part-of-overall-modernization-efforts/.

**Comment by flack** [comment] 2021-11-07 12:32
@mgol well, strictly speaking it was not an issue when 1.12 was released. It cropped up some time later, presumably due to some change in Firefox, so I was hoping that might fall under some "stay compatible with actual browsers" category

**Comment by mgol** [comment] 2021-11-07 15:35
@flack Team's resources are very scarce nowadays. I had a quick look but the button dimensions are fine so I don't know why the outline is so large. If you manage to find a workaround, PRs are welcome. You can also report that as an issue to Firefox, maybe it's a bug they can fix.

**Comment by flack** [comment] 2021-11-07 15:55
alright, I've opened a ticket on Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1739894

It seems to have started in FF 78, i.e. last summer

**Comment by mgol** [comment] 2021-11-18 18:46
Looks like it will get fixed by Firefox; it already looks fine in Nightly 96. Let's wait a bit whether it reaches production and then we'll be able to close it.

**Comment by mgol** [comment] 2021-12-14 09:55
The Firefox fix has propagated to Firefox Developer Edition & Firefox Beta. It should react Firefox stable on 2022-01-11.

**Comment by mgol** [comment] 2022-01-11 14:46
Firefox 96 with the fix has been released, nothing needs to be done on the jQuery UI side. Closing.

**Closed by mgol** 2022-01-11 14:46 UTC
Labels: Bug, Comp: Dialog, Behavior shared with 1.12
