### ISSUE TITLE
Issues using jQuery UI with Vite

### ISSUE THREAD

**Issue by liamkeily** [jquery/jquery-ui#2123] opened 2022-10-25 11:57 UTC
[Vite](https://vitejs.dev/) is now the default frontend tooling for projects like [Laravel](https://laravel.com/) and [VueJS](https://github.com/vuejs/create-vue)

A number of people are having issues with using jQuery UI and Vite together https://github.com/vitejs/vite/discussions/9415#discussioncomment-3959724

**Comment by mgol** [comment] 2022-10-26 14:53
Thanks for the report. Since the issue is already in 1.12, given limited team resources it's not likely to be fixed by the UI team; see the project status at https://blog.jqueryui.com/2021/10/jquery-maintainers-update-and-transition-jquery-ui-as-part-of-overall-modernization-efforts/. PRs are welcome if they're not too complex.

**Comment by mgol** [comment] 2022-10-26 20:13
I think the main issue here is that Vite.js doesn't support AMD but only ECMAScript Modules (ESM) or CommonJS ones. Due to the maintenance mode of jQuery UI, we don't have plans to migrate the module system used.

That said, importing the whole jQuery UI should work, only individual modules should have issues.

**Closed** 2024-06-17 14:00 UTC
Labels: Comp: Build, Behavior shared with 1.12
