### ISSUE TITLE
Mousemove on Autocomplete widget generates tons of cloned elements in hidden accessible

### ISSUE THREAD

**Issue by vitality82** [jquery/jquery-ui#2002] opened 2021-10-28 13:53 UTC
I thought I had a bug in my project after upgrading to jQuery 3.6.0 and jQuery UI - v1.13.0 but this is reproducible with downloading the full jQuery UI as of today:

Not just hovering, but any mouse move on any of the items in the autocomplete result list clones every item inside .ui-helper-hidden-accessible DOM element. Keep going and the debug console scrollbar starts to become very small.

Is this the intention? I have some performance concerns here over cloning so many elements in a hidden DOM, therefore polluting the DOM significantly.

<img width="1568" alt="CleanShot 2021-10-28 at 15 44 49@2x" src="https://user-images.githubusercontent.com/3256598/139269284-2b94e1a1-54a4-4887-9e0a-25aee7eca7a7.png">

**Comment by mgol** [comment] 2021-11-07 10:56
@vitality82 Thanks for the report. Do you see the same behavior with jQuery UI 1.12.1 or not?

**Comment by vitality82** [comment] 2021-11-08 18:48
No, I don't see dupes in the hidden accessible element, just one per each of the result items. Maybe they are triggered on a less sensitive event or perhaps additionally removed (this would be redundant), in any case I tested with: jQuery v1.12.4 on a live production app, and the class `ui-state-focus` is applied on hover of the list items in the original `ui-autocomplete` unordered list. I don't think this class is applied anymore. 

Hope this will help move the ball forward.

**Comment by mgol** [comment] 2021-11-08 23:07
> jQuery v1.12.4

The jQuery version shouldn't matter that much; I was asking whether the same issue appears when jQuery _UI_ 1.12.1 is used.

**Comment by vitality82** [comment] 2021-11-10 21:33
Sorry about the confusion. Prior to the upgrade I was using jQuery UI - v1.11.4 - 2015-05-14 and the same issue didn't show on that version.

**Comment by mgol** [comment] 2021-11-11 07:31
Thanks. Can you check if the issue is still there if you switch to jQuery UI 1.12.1?

**Comment by vitality82** [comment] 2021-11-11 13:19
You can reproduce it just by downloading jQuery-UI both v1.11.4 and v1.12.1 - there is the source of truth - and it looks like the issue also exists in v1.11.4 only a little bit different:

v1.11.4: one item inserted per hover (every time)
v.1.12.1: one item inserted per mouse move (often it inserts a lot more then on item due to the mouse move)

<img width="1099" alt="CleanShot 2021-11-11 at 14 18 15@2x" src="https://user-images.githubusercontent.com/3256598/141304921-76e2482c-b4e5-46d2-964e-760a9aba3c5e.png">

<img width="1110" alt="CleanShot 2021-11-11 at 14 18 46@2x" src="https://user-images.githubusercontent.com/3256598/141304986-e94c5f96-d615-465e-b06c-fc960c012802.png">

**Comment by mgol** [comment] 2021-11-11 16:51
Thanks for the updated info. Since the issue is already in 1.12, given limited team resources it's not likely to be fixed by the UI team; see the project status at https://blog.jqueryui.com/2021/10/jquery-maintainers-update-and-transition-jquery-ui-as-part-of-overall-modernization-efforts/. PRs are welcome, though.

**Comment by jga8** [comment] 2021-11-11 21:26
@mgol and @vitality82, we have the same issue. This issue is not present in jQuery UI 1.12.1, but is present on jQuery UI 1.13.0. (jQuery 3.6.0/macOS/Chrome) and is preventing us from going to 1.13.0. We can easily reproduce this issue.

**Comment by mgol** [comment] 2021-11-11 21:42
@jga8 Thanks for the info. It'd be good to understand why you get different results than @vitality82 who said the issue is in 1.12.1 as well, just not in 1.11.4 (at least not to this extent).

**Comment by jga8** [comment] 2021-11-11 22:21
@mgol to reproduce this, this is what we did: when we copy the code from the demo page, we see the issue. And simply replacing the line 
`<script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>`
with
`<script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>`
makes the issue go away.

Is there any other information we can provide to help?

Screenshot 1 of 2: With 1.12.1, which does not have the error (no duplicates on mousemove )
![1 12 1-no-duplicates](https://user-images.githubusercontent.com/17263353/141376690-dd5d5d84-d26a-4534-8ab0-31e2afb627c8.png)

Screenshot 2 of 2:  With 1.13.0 with the duplicates on mousemove.
![1 13 0-duplicates](https://user-images.githubusercontent.com/17263353/141376973-ef9996c7-b27f-4da3-918e-cd41a2c66751.png)

The following is the code we used 
```
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>jQuery UI Autocomplete - Default functionality</title>
  <link rel="stylesheet" href="//code.jquery.com/ui/1.13.0/themes/base/jquery-ui.css">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-3.6.0.js"></script>
  <script src="https://code.jquery.com/ui/1.13.0/jquery-ui.js"></script>
  <script>
  $( function() {
    var availableTags = [
      "ActionScript",
      "AppleScript",
      "Asp",
      "BASIC",
      "C",
      "C++",
      "Clojure",
      "COBOL",
      "ColdFusion",
      "Erlang",
      "Fortran",
      "Groovy",
      "Haskell",
      "Java",
      "JavaScript",
      "Lisp",
      "Perl",
      "PHP",
      "Python",
      "Ruby",
      "Scala",
      "Scheme"
    ];
    $( "#tags" ).autocomplete({
      source: availableTags
    });
  } );
  </script>
</head>
<body>
 <div class="ui-widget">
  <label for="tags">Tags: </label>
  <input id="tags">
</div>
 </body>
</html>
```

**Comment by vitality82** [comment] 2021-11-12 06:27
> @jga8 Thanks for the info. It'd be good to understand why you get different results than @vitality82 who said the issue is in 1.12.1 as well, just not in 1.11.4 (at least not to this extent).

I can see the major issue in 1.13.0 and 1.12.1. The way I've tested is to download jQuery UI for both versions and tested on latest Chrome and Firefox.

On 1.11.1 the DOM appending also has dupes but only when you hover a full item in the result list.

**Comment by mgol** [comment] 2021-12-01 21:49
OK, it looks like at least one of the issues is specific to 1.13. Thanks for all the info, I'll have a look if no one beats me to it.

**Comment by bbenjamin** [comment] 2021-12-08 14:05
This looks to be related to a change in menu.js that was introduced in 1.13
https://github.com/jquery/jquery-ui/blob/6d072c596a81d99a77fc36c14caf3eb3a803689e/ui/widgets/menu.js#L117
Adds this to the event listeners:
`"mousemove .ui-menu-item": "_activateItem",`

The `_activateItem` callback triggers a focus event that results in the autocomplete widget adding the item to the aria-live region. _activeItem will return early when the target has the active state class: `if ( target.is( ".ui-state-active" ) ) {
			return;
		}`, but the target does not (yet?) contain that class.

**Closed** 2022-01-05 10:35 UTC
Labels: Bug, Comp: Autocomplete, Behavior different from 1.12

**Comment by vitality82** [comment] 2022-01-05 11:18
Awesome work! Just curious will there be a minor release with this included patch?

**Comment by mgol** [comment] 2022-01-05 11:42
Yes, we'll release it in 1.13.1 when it's ready. For now we still plan to land one more patch before this release.

**Comment by mgol** [comment] 2022-01-20 23:36
jQuery UI 1.13.1 including a fix for this issue has been released: https://blog.jqueryui.com/2022/01/jquery-ui-1-13-1-released/.
