### ISSUE TITLE
IE filter property has incorrect value for the widget-overlay v1.13

### ISSUE THREAD

**Issue by Diazole** [jquery/jquery-ui#2190] opened 2023-10-17 11:22 UTC
IE filter property values were updated to strings by https://github.com/jquery/jquery-ui/pull/1939.

However, the filter value for the widget-overlay hasn't been updated in the output CSS file (https://github.com/jquery/jquery-ui/blob/1.13.2/dist/themes/base/theme.css#L441).

All of the other filters have been updated to strings in the output file, so I'm not sure why this one wasn't?

**Comment by Diazole** [comment] 2023-10-17 11:57
The v1.13.2 stable release has:

```css
/* Overlays */
.ui-widget-overlay {
	background: #aaaaaa;
	opacity: .003;
	-ms-filter: Alpha(Opacity=.3); /* support: IE8 */
}
```

But the base theme for v1.13.2 has:

```css
/* Overlays */
.ui-widget-overlay {
	background: #aaaaaa/*{bgColorOverlay}*/ /*{bgImgUrlOverlay}*/ /*{bgOverlayXPos}*/ /*{bgOverlayYPos}*/ /*{bgOverlayRepeat}*/;
	opacity: .3/*{opacityOverlay}*/;
	-ms-filter: "alpha(opacity=30)"/*{opacityFilterOverlay}*/; /* support: IE8 */
}
```

So not only is the filter different, the opacity is too?

**Comment by mgol** [comment] 2023-10-19 15:51
The values in curly braces are variable names that are supposed to substitute the default values, based on the theme used.

We probably need to update the `opacityFilterOverlay` values.

It looks like the issue is in themeroller: https://github.com/jquery/jquery-ui-themeroller/blob/71ccc63fbe0744987743ecf83bcedde460c3165a/lib/themeroller.js#L119-L122.

Would you like to submit a PR?

**Comment by mcanepa** [comment] 2024-01-03 01:46
@mgol does [#15](https://github.com/jquery/jquery-ui-themeroller/pull/15) fix this?

**Comment by mgol** [comment] 2024-04-20 23:23
PR for `jquery-ui-themeroller` at https://github.com/jquery/jquery-ui-themeroller/pull/19, I'll also submit a separate one for the Download Builder which currently has a separate version of themeroller (I'll wait with straightening this out until jQuery UI 1.14).

**Comment by mgol** [comment] 2024-04-21 15:39
PR for the Download Builder repo: https://github.com/jquery/download.jqueryui.com/pull/612

**Comment by mgol** [comment] 2024-04-21 15:49
Re-opening since only the `jquery-ui-themeroller` PR landed so far.

**Closed** 2024-04-21 20:51 UTC
Labels: Bug, Behavior different from 1.12, Comp: Theme
